### ISSUE TITLE
Read up on Preprocessing / Colmap

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#21]
* What is it and what can we do with it? 
* Create small presentation for rest of team

**Comment by unweytvanfern** [comment]
Colmap as far as we are concerned, generates pointclouds in a sparse and dense variant. It does so using Structure from Motion. With this it determines the locations of our cameras.

In Pre-Processing, we are looking to get camera positions/paths for our source images. 
The Images saved are in their original resolution and in progressively downscaled variants.
A pointcloud is generated by Colmaps but isnt needed for splatfacto.

Most of Colmaps other functionality because of this less directly relevant for out splats.

(ns-process-data is not bound to Colmap but can also use hloc, another SfM tool.)
Different camerytypes can be adjusted for here, but splatfacto is only compatible with the default ('perspective').
We can add evaluation data in oder to improve the accuracy of our results with --eval-data.
--matching-method can be alternatively set to exhaustive (or sequential for frames of videos).
The exhaustive option is best used at below ~200 source images which would work well with our current plans to capture our location in batches. 
While it has been very effective at improving a scene with low initial matches but could turn out to be marginal with higher quality source images.
