### ISSUE TITLE
Revisit Docker Image creation

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#58]
is it worth it? is it feasable?

**Comment by FabiKogWi** [comment]
It is feasible. After previously failing due to my very incomplete knowledge about docker a simple docker image based on the node:21-alpine3.19 image works for running the base project without any additional splats (With these it works as well, but the docker image gets very large). Next another docker image which maybe stores the splats could be created.
